//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int e_id { get; set; }
        public string e_name { get; set; }
        public Nullable<int> e_salary { get; set; }
        public Nullable<int> e_age { get; set; }
        public string e_gender { get; set; }
        public string e_dept { get; set; }
    }
}
